[[headers]]
  for = "/.well-known/matrix/*"

  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/.well-known/matrix/*"
  to = "https://matrix.sthom.kiwi/.well-known/matrix/:splat"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
