[[headers]]
  for = "/.well-known/matrix/*"

  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/.well-known/matrix/*"
  to = "https://matrix.sthom.kiwi/.well-known/matrix/:splat"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"

# Redirects for old content. Keep this for at least a year or two, after which, review referrer traffic
[[redirects]]
  from = "/posts/*"
  to = "https://archive-2020.sthom.kiwi/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/projects/*"
  to = "https://archive-2020.sthom.kiwi/:splat"
  status = 301
  force = true
